# Generated by Django 4.0.3 on 2023-03-09 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0007_alter_salesrecord_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesperson',
            name='employee_num',
            field=models.IntegerField(unique=True),
        ),
    ]
