# Generated by Django 4.0.3 on 2023-03-15 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0008_alter_salesperson_employee_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_num',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
