# Generated by Django 4.0.3 on 2023-03-10 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0003_rental'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='rentals',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rental', to='service_rest.appointment'),
        ),
    ]
