# Generated by Django 4.0.3 on 2023-03-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0004_appointment_rentals_alter_rental_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='rental_end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='rental_start',
            field=models.DateTimeField(null=True),
        ),
    ]
