# Generated by Django 4.0.3 on 2023-03-10 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0005_rental_rental_end_rental_rental_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='returned',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
